try: 
    a = 455/5
except Exception as e:
    print(e)

# Gets excuted when there in no {try block error}
else:
    print("Hay, I am good")
    